
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:

   CI:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v3
       - name: Install modules
         run: npm install
       - name: Run test
         run: npm test
     
   build_and_deploy:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v3
      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTH_DEV_CA246 }}
          channelId: live
          projectId: auth-dev-ca246
 

  
   Slack:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: rtCamp/action-slack-notify@v2
    
    
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_TITLE: ${{ job.status }}
      SLACK_COLOR: ${{ job.status }}
