
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:

   tests:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v3
       - name: Install modules
         run: npm install
       - name: Run test
         run: npm test
     

 
   build_and_deploy-live:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTH_TEST_CA246 }}
          channelId: live
          projectId: auth-dev-ca246

  
   Slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: rtCamp/action-slack-notify@v2
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_ICON_EMOJ: :bell
