on: push
name: Slack 
jobs:
  slackNotification:
    name: Slack Notis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 
